# Generated by Django 3.0.2 on 2020-09-19 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=255)),
                ('registered_at', models.DateTimeField()),
                ('registered_by', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Outflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registered_at', models.DateTimeField()),
                ('registered_by', models.CharField(max_length=55)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Inflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registered_at', models.DateTimeField()),
                ('registered_by', models.CharField(max_length=55)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashflow.Category')),
            ],
        ),
    ]
