# Generated by Django 3.0.2 on 2020-09-20 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.Category'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.Category'),
        ),
    ]
