# Generated by Django 3.0.2 on 2020-09-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_auto_20200920_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registered_at', models.DateTimeField()),
                ('registered_by', models.CharField(max_length=55)),
                ('inflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.Inflow')),
                ('outflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashflow.Outflow')),
            ],
        ),
    ]
