# Generated by Django 3.1.1 on 2021-01-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0004_auto_20201021_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='report',
            name='balance_percent',
        ),
        migrations.RemoveField(
            model_name='report',
            name='description',
        ),
        migrations.RemoveField(
            model_name='report',
            name='inflow_values',
        ),
        migrations.RemoveField(
            model_name='report',
            name='name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='outflow_values',
        ),
        migrations.AddField(
            model_name='report',
            name='inflow_outflow_dif_values',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='report',
            name='inflow_sum_values',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='report',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='outflow_sum_values',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='report',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='registered_by',
            field=models.CharField(default='', max_length=55),
        ),
    ]
